version: '3'
services:
  redis:
    image: redis
    container_name: redis

  mysql:
    image: mysql:8.0.32
    container_name: mysql8.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='+08:00'
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3306:3306"